// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macOS;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_yl2Z-LykHK98B7KW7B9FVK_V0MXk55o',
    appId: '1:23916141513:web:050ceae2989755e61a2618',
    messagingSenderId: '23916141513',
    projectId: 'polished-signal-2pnh2',
    authDomain: 'polished-signal-2pnh2.firebaseapp.com',
    storageBucket: 'polished-signal-2pnh2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_yl2Z-LykHK98B7KW7B9FVK_V0MXk55o',
    appId: '1:23916141513:android:ca9d19fc9b441111111111',
    messagingSenderId: '23916141513',
    projectId: 'polished-signal-2pnh2',
    storageBucket: 'polished-signal-2pnh2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_yl2Z-LykHK98B7KW7B9FVK_V0MXk55o',
    appId: '1:23916141513:ios:ca9d19fc9b441111111111',
    messagingSenderId: '23916141513',
    projectId: 'polished-signal-2pnh2',
    storageBucket: 'polished-signal-2pnh2.firebasestorage.app',
    iosBundleId: 'com.example.sunita_school_portal_app',
  );

  static const FirebaseOptions macOS = FirebaseOptions(
    apiKey: 'AIzaSyD_yl2Z-LykHK98B7KW7B9FVK_V0MXk55o',
    appId: '1:23916141513:ios:ca9d19fc9b441111111111',
    messagingSenderId: '23916141513',
    projectId: 'polished-signal-2pnh2',
    storageBucket: 'polished-signal-2pnh2.firebasestorage.app',
    iosBundleId: 'com.example.sunita_school_portal_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_yl2Z-LykHK98B7KW7B9FVK_V0MXk55o',
    appId: '1:23916141513:web:050ceae2989755e61a2618',
    messagingSenderId: '23916141513',
    projectId: 'polished-signal-2pnh2',
    authDomain: 'polished-signal-2pnh2.firebaseapp.com',
    storageBucket: 'polished-signal-2pnh2.firebasestorage.app',
  );
}
